version: '3.4'

services:

  ca.org1.example.com:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ca.org1.example.com_v4
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.org1.example.com
      - FABRIC_CA_SERVER_TLS_ENABLED=false
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/ee6728254f19d503c2598c18ba8daa7ee36c1d3f7c400175fceca0e2e95bb0d5_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.name ca.org1.example.com --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/ee6728254f19d503c2598c18ba8daa7ee36c1d3f7c400175fceca0e2e95bb0d5_sk -b admin:adminpw -d'
    volumes:
      - ./config/crypto-config/peerOrganizations/org1.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
      - ./config/ca/ca1/:/etc/hyperledger/fabric-ca-server
